package com.earthdawn.model.enums;

public enum ActionType {
    MELEE_ATTACK,
    RANGED_ATTACK,
    SPELL_ATTACK,
    TALENT_TEST,
    SKILL_TEST,
    RECOVERY_TEST,
    INITIATIVE,
    EFFECT_ADDED,
    EFFECT_REMOVED,
    VALUE_CHANGED,
    ROUND_CHANGE,
    COMBAT_OPTION,
    FREE_ACTION,
    DODGE,
    STAND_UP,
    AUFSPRINGEN,
    THREADWEAVE,
    SPELL_CAST,
    TAUNT,
    ACROBATIC_DEFENSE,
    COMBAT_SENSE,
    DISTRACT,
    IRON_WILL
}
