spring.datasource.url=jdbc:postgresql://localhost:5432/earthdawn
spring.datasource.username=earthdawn
spring.datasource.password=earthdawn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081

logging.level.com.earthdawn=DEBUG
server.error.include-message=always
server.error.include-stacktrace=never
